{% set python_min = "3.10" %}
{% set name = "timescoring" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecd7e68c4df7e5469aedb572588e144feeee53a58aa0a915616a347d7701e940

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.7.1
    - numpy >=1.24.3
    - nptyping >=2.5.0

test:
  imports:
    - timescoring
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/esl-epfl/epilepsy_performance_metrics
  summary: Library for measuring performance of time series classification
  description: |
    This library implements sample and event based scoring for binary time
    series classification.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danjjl
