{% set name = "timescoring" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 372264ff54528395b294505437bf8e88a32ed9e3529866dd4e53a72ea51c8a4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - matplotlib-base >=3.7.1
    - numpy >=1.24.3
    - nptyping >=2.5.0

test:
  imports:
    - timescoring
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/esl-epfl/epilepsy_performance_metrics
  summary: Library for measuring performance of time series classification
  description: |
    This library implements sample and event based scoring for binary time
    series classification.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danjjl
